name: Deploy to Amazon ECS

on:
  pull_request:
    types: closed
    branches: ['master']

jobs:
  deploy:
    if: github.event.pull_request.merged == true && github.event.pull_request.base.ref == 'master' && github.event.pull_request.head.ref == 'develop'
    name: Deploy
    runs-on: ubuntu-latest
    environment: production
    outputs:
          duration: ${{ steps.duration.outputs.duration }}

    steps:
    - name: Record Start Time
      run: echo "START_TIME=$(date +%s)" >> $GITHUB_ENV
